In [1]:
#code

def creating_gen(index):  
    months = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']  
    yield months[index]  
    yield months[index+2]  
next_month = creating_gen(3)  
print(next(next_month), next(next_month))  

apr jun


In [2]:
#Code

month = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']  
converting_list = tuple(month)  
print(converting_list)  
print(type(converting_list))  

('jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec')
<class 'tuple'>


In [3]:
#Code

import numpy  
#method 1  
array_1 = numpy.array([])  
print(array_1)  
#method 2  
array_2 = numpy.empty(shape=(3,3))  
print(array_2)  

[]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.90505033e-321]
 [1.30927140e-311 6.05951278e-306 0.00000000e+000]]


In [4]:
#5) Tell the output of the following code?
#Code

import array  
a = [4, 6, 8, 3, 1, 7]  
print(a[-3])  
print(a[-5])  
print(a[-1])  

3
6
7


In [5]:
#Code

Print=( sum(range(1,102)) )  
print

<function print>

In [6]:
print(sum(range(1,102)))

5151


In [7]:
#Code

global_var = 0  
def modify_global_var():  
    global global_var # Setting global_var as a global variable  
    global_var = 10  
def printing_global_var():  
    print(global_var) # There is no need to declare global variable  
modify_global_var()  
printing_global_var() # Prints 10

10


In [8]:
#Code

n = int(input("Enter number: "))  
  
reverse = 0  
  
while(n>0):  
    digit = n%10  
    reverse = reverse*10+digit  
    n=n//10  
print("The reverse of the number:",reverse)  


Enter number: 09876
The reverse of the number: 6789


In [9]:
#Code

list_comp = [i for i in range(4)]  
print(list_comp)  

[0, 1, 2, 3]


In [10]:
#Code

dictt = {i : i+2 for i in range(10)}  
print(dictt)   

{0: 2, 1: 3, 2: 4, 3: 5, 4: 6, 5: 7, 6: 8, 7: 9, 8: 10, 9: 11}


In [11]:
#Code

# Python program to show how global variables and local variables are different  
var = 56  
# Creating a function  
def addition():  
    var1 = 7  
    c = var + var1  
    print("In local scope: ", var1)  
    print("Adding a global scope and a local scope variable: ", c)  
addition()  
print("In global scope: ", var)  

In local scope:  7
Adding a global scope and a local scope variable:  63
In global scope:  56


In [12]:
#Code

# Python program to show the difference between a list and an array  
  
# Importing array module  
import array as arr  
  
# Creating an array and a list  
array_1 = arr.array("i", [3, 6, 2, 7, 9, 5])  
list_1 = [4, 'Interview', 7.20]  
  
print(array_1)  
print(list_1)  
  
# Trying to create an array with multiple data types  
try:  
    array_2 = arr.array("i", [3, 7, 3, "Interview"])  
except Exception as e:  
    print(e)  

array('i', [3, 6, 2, 7, 9, 5])
[4, 'Interview', 7.2]
an integer is required (got type str)


In [13]:
#Code

# Python program to explain __init__  
  
class Student:  
    def __init__(self, st_name, st_class, st_marks):  
        self.st_name = st_name  
        self.st_class = st_class  
        self.st_marks = 67  
S1 = Student("Itika", 10, 67)  
print(S1.st_name)  
print(S1.st_class)  

Itika
10


In [14]:
#Code

# Python program to show how to use lambda functions  
  
# Creating a lambda function for addition  
sum_ = lambda x, y, z : x + y + z  
print("Sum using lambda function is: ", sum_(4, 6, 8))  

Sum using lambda function is:  18


In [15]:
#Code

# Python program to show to randomise elements of a list  
  
# Importing the random module  
import random  
list_ = ["Python", "Interview", "Questions", "Randomise", "List"]  
print("Original list: ", list_)  
random.shuffle(list_)  
print("After randomising the list: ", list_) 

Original list:  ['Python', 'Interview', 'Questions', 'Randomise', 'List']
After randomising the list:  ['Python', 'Interview', 'Randomise', 'List', 'Questions']


In [16]:
#Code

# Python program to show how to convert a string to lower case  
  
string = 'JAVATPOINT'  
print(string.lower())  

javatpoint


In [17]:
#Code

# Python program to show how to write a docstring  
  
""" 
This is a docstring. 
We write docstrings to explain a program. 
This program will multiply two numbers and then display the output. 
"""  
a = 39  
b = 45  
c = a * b  
print("Result of multiplication: ", c) 

Result of multiplication:  1755


In [18]:
#Code

# Python program to show how to add elements to an array  
  
array = arr.array('d', [1 , 2 ,3] )  
array.append(8) # appending will add an element to the end of the array  
print(array)  
array.extend([4,6,9]) # extending will add elements by looping through the given iterable  
print(array)  
array.insert(2, 9) # inserting will add the element at the specified index  
print(array)  

array('d', [1.0, 2.0, 3.0, 8.0])
array('d', [1.0, 2.0, 3.0, 8.0, 4.0, 6.0, 9.0])
array('d', [1.0, 2.0, 9.0, 3.0, 8.0, 4.0, 6.0, 9.0])


In [19]:
#Code

# Python program to show how to remove elements from a Python array  
  
array = arr.array('d', [1, 3, 8, 1, 4, 8, 2, 4])  
print(array.pop()) # By default it will remove and return the last element of the array  
print(array.pop(5)) # It will return and remove the element present at 5th index  
array.remove(1) # It will remove only the first occurrence of the element - 1 from the array  
print(array)  

4.0
8.0
array('d', [3.0, 8.0, 1.0, 4.0, 2.0])


In [20]:
# Python program to show how to make an empty class  
  
class my_class:  
    pass  
object_ = my_class()  
object_.name = "Javatpoint"  
print("Name = ", object_.name)  

Name =  Javatpoint


In [21]:
#20) Make a Python script that checks if a given number is prime.
#Code

# Python program to check if a number is prime or not  
  
# Declaring a variable  
n = 37  
if n == 2:  
    print("2 is a prime number")  
  
if n != 1:  
    for i in range(2, n):  
        if n % i == 0:  
            print("The given number is a composite number")  
            break  
        if i == n-1:  
            print("The given number is a prime number")  
else:  
    print("1 is not a prime number")  

The given number is a prime number


In [ ]:
#Code

num = 1101001  
while(num > 0):  
    l = num % 10  
     
if l!=0 and l!=1:  
         
    print("given number is not binary")  
         
break  
     
num = num // 10  
     
if num == 0:  
         
    print("given number is binary")  

In [ ]:
#22) Compute the LCM of two given numbers using Python code.
#Following is the code

#Code

num_1 = 24   
num_2 = 92   
if num_1 > num_2:    
     
greater_num = num_1    
else:   
     
greater_num = num_2    
while(True):    
     
if((greater_num % num_1 == 0) and (greater_num % num_2 == 0)):    
         
lcm = greater_num  
         
break    
     
greater_num += 1    
print("LCM of", num_1, "and", num_2, "=", greater_num)  

In [ ]:
#Code

string = 'Javatpoint'  
result=''  
for s in string:    
if s in ('a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U'):       
s = ''    
result += s  
print("Required string without vowels is:", result) 

In [ ]:
#24) Write a Python code to reverse a given list.
#Following is the code.

array = [23, 12, 5, 24, 23, 76, 86, 24, 86, 24, 75]  
  
print("Reverse order of array is")  
# Reversing the given array  
for i in range(len(array)-1, -1, -1):       
     
print(array[i], end=' ')  

In [ ]:
#Q25. Write a program in Python to produce Star triangle.

def pyfunc(r):
    for x in range(r):
        print(' '*(r-x-1)+'*'*(2*x+1))    
pyfunc(9)

In [ ]:
#Q26. Write a sorting algorithm for a numerical dataset in Python.
#Ans: The following code can be used to sort a list in Python:


list = ["1", "4", "0", "6", "9"]
list = [int(i) for i in list]
list.sort()
print (list)

In [ ]:
#27. Which of the following statements create a dictionary? (Multiple Correct Answers Possible)
a) d = {}
b) d = {“john”:40, “peter”:45}
c) d = {40:”john”, 45:”peter”}
d) d = (40:”john”, 45:”50”)
Answer: b, c & d. 

Dictionaries are created by specifying keys and values.

In [ ]:
#Source Code
# This program prints Hello, world!

print('Hello, world!')